name: 'Juan Sepulveda Design '
favicon: null
layout_spectrum: 0
typography_spectrum: 0.34203
title: 'Industrial Designer | Illustrator | Visual Artist'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#474747'
    - '#6f6f6f'
    - '#c3c3c3'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 1
purpose: []
